[[redirects]]
  # Handle routing for single-page applications
  from="/*"
  to="/index.html"
  status=200

  [build]
  # Specify Node.js version
  node_version = "16"

  # Directory to deploy (adjust if different in your project)
  publish = "build"

  # Build command for most React apps (adjust if different in your project)
  command = "npm start"


